server:
  port: 8080

spring:
  application:
    name: kafka-spring-2025

  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:test_db;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:29092
    topic: board-topic
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    com.example.kafka: DEBUG
    org.springframework.kafka: DEBUG